services:

  pn-dev-container:
    container_name: pn-dev-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command:
      - sleep infinity
    depends_on:
      - pn-redis
    environment:
      - PORT=80
      - REDIS_HOST=pn-redis:6379
    ports:
      - "8080:80"
