services:

  pn-dev-container:
    container_name: pn-dev-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    command:
      - sleep infinity
    depends_on:
      - pn-redis
    environment:
      - PORT=80
      - REDIS_HOST=pn-redis:6379
      - GOROOT=/usr/local/go
      - GOPATH=/go
      - GO111MODULE=on
    ports:
      - "8080:80"
