on:
  push:
    branches:
      - master

jobs:
  ci-job:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Run Deployment
        run: ./.ci/deploy.sh $APP_ID $APP_KEY $TENANT_ID $SUBSCRIPTION_ID $RESOURCE_GROUP
        shell: bash
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_KEY: ${{ secrets.APP_KEY }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
